/*import { Suspense } from "react"


// three
import { useLoader } from '@react-three/fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'


function Scene() {
  const gltf = useLoader(GLTFLoader, '/scene_4.glb')
  return (
    <Suspense fallback={null}>
      <primitive object={gltf.scene} />
    </Suspense>
  )
}


export default Scene
*/

 

// Auto-generated by: https://github.com/pmndrs/gltfjsx

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function Model(props) {
  const { nodes, materials } = useGLTF("/scene_4.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube156.geometry}
        material={materials["editor Material.002"]}
        position={[0, 1.16, 1.98]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.01, -1.05, -0.76]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube157.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 1.93, 2.2]}
        rotation={[0, 0, -Math.PI]}
        scale={[0.01, 0.03, 0.37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube158.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 1.79, 2.05]}
        rotation={[0, 0, -Math.PI]}
        scale={[0.01, 0.03, 0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube159.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 1.46, 2.34]}
        scale={[0.01, 0.03, 0.26]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube160.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 1.62, 2.02]}
        scale={[0.01, 0.03, 0.58]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube161.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 1.04, 2.2]}
        rotation={[0, 0, -Math.PI]}
        scale={[0.01, 0.03, 0.37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube163.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 0.89, 2.32]}
        scale={[0.01, 0.03, 0.26]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube155.geometry}
        material={materials["editor Material.002"]}
        position={[0, 0.53, 0]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.01, -0.38, -0.76]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube169.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 0.71, 0.47]}
        scale={[0.01, 0.03, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube170.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 0.71, 0.1]}
        scale={[0.01, 0.03, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube171.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 0.57, 0.47]}
        scale={[0.01, 0.03, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube172.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 0.57, 0.1]}
        scale={[0.01, 0.03, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube173.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 0.45, 0.47]}
        scale={[0.01, 0.03, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube174.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 0.45, 0.1]}
        scale={[0.01, 0.03, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube154.geometry}
        material={materials["editor Material.002"]}
        position={[0, 1.56, 0]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.01, -0.6, -0.76]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube162.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 1.96, 0.52]}
        scale={[0.01, 0.03, 0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube164.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 1.96, 0.1]}
        scale={[0.01, 0.03, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube165.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 1.83, 0.47]}
        scale={[0.01, 0.03, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube166.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 1.83, 0]}
        scale={[0.01, 0.03, 0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube167.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 1.69, 0.47]}
        scale={[0.01, 0.03, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube168.geometry}
        material={materials["text Material.002"]}
        position={[0.05, 1.69, 0.1]}
        scale={[0.01, 0.03, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube153.geometry}
        material={materials["editor Material.002"]}
        position={[0, 2.53, 0.97]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.01, -0.14, -1.69]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube152.geometry}
        material={materials["Input Material.002"]}
        position={[0.04, 2.53, 0.97]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.01, -0.09, -0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube150.geometry}
        material={materials["Button Material.002"]}
        position={[0.03, 2.52, 0.35]}
        scale={[0.03, 0.08, 0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube151.geometry}
        material={materials["editor Material.002"]}
        position={[0, 1.27, 3.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.01, -0.14, -1.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube149.geometry}
        material={materials["Button Material.002"]}
        position={[0.03, 1.75, 3.11]}
        scale={[0.03, 0.08, 0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube148.geometry}
        material={materials["Button Material.002"]}
        position={[0.03, 1.45, 3.11]}
        scale={[0.03, 0.08, 0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube147.geometry}
        material={materials["Button Material.002"]}
        position={[0.03, 1.19, 3.11]}
        scale={[0.03, 0.08, 0.08]}
      />
    {/*     <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve048.geometry}
        material={materials["Cabels Material.002"]}
        position={[0.01, 1.64, 0.92]}
        rotation={[-2, 0.05, Math.PI / 2]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve049.geometry}
        material={materials["Cabels Material.002"]}
        position={[0.01, 1.54, 0.92]}
        rotation={[-2, 0.05, Math.PI / 2]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve050.geometry}
        material={materials["Cabels Material.002"]}
        position={[0.01, 1.47, 0.92]}
        rotation={[-2, 0.05, Math.PI / 2]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve052.geometry}
        material={materials["Cabels Material.002"]}
        position={[0.01, 0.94, 0.06]}
        rotation={[3.05, 0.05, Math.PI / 2]}
        scale={[0.17, 0.38, 0.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve053.geometry}
        material={materials["Cabels Material.002"]}
        position={[0.01, 0.93, 0.13]}
        rotation={[3.05, 0.05, Math.PI / 2]}
        scale={[0.17, 0.38, 0.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve051.geometry}
        material={materials["Cabels Material.002"]}
        position={[0.01, 2.26, 0.31]}
        rotation={[0.09, -0.05, -Math.PI / 2]}
        scale={[0.2, 0.38, 0.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve054.geometry}
        material={materials["Cabels Material.002"]}
        position={[0.01, 2.24, 0.24]}
        rotation={[0.09, -0.05, -Math.PI / 2]}
        scale={[0.2, 0.38, 0.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve055.geometry}
        material={materials["Cabels Material.002"]}
        position={[0.01, 2.26, 1.71]}
        rotation={[3.05, 0.05, Math.PI / 2]}
        scale={[0.2, 0.38, 0.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve056.geometry}
        material={materials["Cabels Material.002"]}
        position={[0.01, 2.24, 1.78]}
        rotation={[3.05, 0.05, Math.PI / 2]}
        scale={[0.2, 0.38, 0.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve057.geometry}
        material={materials["Cabels Material.002"]}
        position={[0.01, 1.47, 2.82]}
        rotation={[2, -0.05, -Math.PI / 2]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve058.geometry}
        material={materials["Cabels Material.002"]}
        position={[0.01, 1.75, 2.82]}
        rotation={[-2, 0.05, Math.PI / 2]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve059.geometry}
        material={materials["Cabels Material.002"]}
        position={[0.01, 1.17, 2.82]}
        rotation={[-2, 0.05, Math.PI / 2]}
        scale={0.38}
      />
      */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube175.geometry}
        material={materials["Wireframe cube Material.002"]}
        position={[-0.09, 1.17, 1.99]}
        scale={[0.19, 1.14, 0.87]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text007.geometry}
        material={materials["GeoText Material 1.001"]}
        position={[0, 2.47, 3.25]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.29}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text006.geometry}
        material={materials["GeoText Material 2.001"]}
        position={[0, 1.16, 1.13]}
        rotation={[2.01, 0.28, -1.91]}
        scale={0.22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text005.geometry}
        material={materials["GeoText Material 3.001"]}
        position={[0, 0.83, 2.98]}
        rotation={[-2.01, -0.28, 1.23]}
        scale={0.22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text004.geometry}
        material={materials["GeoText Material 1.001"]}
        position={[0.16, 0.88, -0.19]}
        rotation={[1.71, -0.33, -0.65]}
        scale={0.22}
      />
    </group>
  );
}

useGLTF.preload("/scene_4.glb");


export default Model
